# Generated by Django 5.0.6 on 2024-09-20 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newsletter',
        ),
    ]
