# Generated by Django 5.0.6 on 2024-06-30 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_comment_published_date_comment_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='product',
            new_name='pro',
        ),
    ]
