# Generated by Django 5.0.6 on 2024-09-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_product_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.CharField(choices=[('بدون گارانتی', 'Without Warranty'), ('شش ماهه', 'Six Months'), ('یک ساله', 'One Year')], default='بدون گارانتی', max_length=20),
        ),
    ]
