# Generated by Django 5.0.6 on 2024-07-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_product_comment_pro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorys',
            name='Discoust',
        ),
        migrations.AddField(
            model_name='product',
            name='Discoust',
            field=models.IntegerField(default=0),
        ),
    ]
