# Generated by Django 5.0.6 on 2024-09-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_product_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.CharField(choices=[('no_warranty', 'بدون گارانتی'), ('six_months', 'شش ماهه'), ('one_year', 'یک ساله')], default='no_warranty', max_length=20),
        ),
    ]
