# Generated by Django 5.0.6 on 2024-08-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_product_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Ready_to_send',
            field=models.BooleanField(default=False),
        ),
    ]
