# Generated by Django 5.0.6 on 2024-09-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_product_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stars',
            field=models.IntegerField(default=0, max_length=255),
        ),
    ]
