# Generated by Django 5.0.6 on 2024-09-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_adresses_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.AddField(
            model_name='comment',
            name='Innovation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='Longevity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='Services',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='beauty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='quality',
            field=models.IntegerField(default=0),
        ),
    ]
