# Generated by Django 5.0.6 on 2024-09-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_comment_email_comment_innovation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
