# Generated by Django 5.0.6 on 2024-09-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_product_author_product_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='telephon',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='title',
        ),
    ]
