# Generated by Django 5.0.6 on 2024-09-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_contact_answer_alter_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='answer',
            field=models.TextField(default=None, null=True),
        ),
    ]
